import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./utils/theme.provider";
import { Provider } from "./Provider";
import { Toaster } from "react-hot-toast";
import Custom from "./utils/custom"; // ✅ new client component
import Header from "./component/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({ 
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {  
  title: "Elearning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header/> 
            <Custom>{children}</Custom>
            <Toaster position="top-right" reverseOrder={false} />
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
